language: java
sudo: false # faster builds

jdk:
    - oraclejdk11
    - oraclejdk10
    - oraclejdk9
    - oraclejdk8

script: "mvn clean package"

after_success:
  - bash <(curl -s https://codecov.io/bash)
